<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php if ($_description = $block->getCurrentCategory()->getDescription()): ?>
    <div class="category-description">
    <?php
        $_desc = $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_description, 'description');
        $_desc = str_replace('<p>','', $_desc);
        $_desc = str_replace('</p>','', $_desc);
        $_descHtml   = '';


        $_descHtml = '<style> .breadcrumb.text-center:after { content: "'. $_desc .'" !important; display: block;font-size: 20px;}</style>';

        /* @escapeNotVerified */ echo $_descHtml;

    ?>
        <?php /* @escapeNotVerified */ //echo $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_description, 'description') ?>
    </div>
<?php endif; ?>
