<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php 
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$themeSettings = $themeHelper->getThemeSettings();
?>
<?php 
	$om = \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager = $om->get('Magento\Store\Model\StoreManagerInterface');
	$currentStore = $storeManager->getStore();
	$currentUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<?php if($themeSettings['contact_google_map']['display_google_map'] && ($themeSettings['contact_google_map']['address_google_map'] !='')): ?>
	<?php $image = $currentUrl.'map/'.$themeSettings['contact_google_map']['pin_google_map'] ?>
	<div class="map-container nopadding" style="margin-bottom: 30px;">
		<!--div id="map" style="height: 500px;"></div-->
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3762.6620478279387!2d-99.21394508538042!3d19.427002586887465!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x85d201f52c221c1b%3A0xadd1f18a29744bd9!2sAvenida+Prado+Norte+460%2C+Lomas+-+Virreyes%2C+Lomas+de+Chapultepec+V+Secc%2C+11000+Ciudad+de+M%C3%A9xico%2C+CDMX!5e0!3m2!1sen!2smx!4v1545197786158" width="100%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>
	
	<script src="http://maps.google.com/maps/api/js?key=AIzaSyBZqRRixboWggokB3fxhMpFbR9cIfe5pI4"></script>
	<script type="text/javascript">
		require([
		'jquery'
	], function(jQuery){
		(function($) {
			var address = '<?php echo $themeSettings['contact_google_map']['address_google_map'] ?>';
			var html = '<?php echo $themeSettings['contact_google_map']['html_google_map'] ?>';
			var image = '<?php echo $image ?>';
			$.ajax({
				type: "GET",
				dataType: "json",
				url: "http://maps.googleapis.com/maps/api/geocode/json",
				data: {'address': address,'sensor':false},
				success: function(data){
					if(data.results.length){
						latitude = data.results[0].geometry.location.lat;
						longitude = data.results[0].geometry.location.lng;
						
						var locations = [
					[html, latitude, longitude, 2]
					];
				
					var map = new google.maps.Map(document.getElementById('map'), {
					  zoom: 14,
						scrollwheel: false,
						navigationControl: true,
						mapTypeControl: false,
						scaleControl: false,
						draggable: true,
						center: new google.maps.LatLng(latitude, longitude),
					  mapTypeId: google.maps.MapTypeId.ROADMAP
					});
				
					var infowindow = new google.maps.InfoWindow();
				
					var marker, i;
				
					for (i = 0; i < locations.length; i++) {  
				  
						marker = new google.maps.Marker({ 
						position: new google.maps.LatLng(locations[i][1], locations[i][2]), 
						map: map 
						});
				
				
					  google.maps.event.addListener(marker, 'click', (function(marker, i) {
						return function() {
						  infowindow.setContent(locations[i][0]);
						  infowindow.open(map, marker);
						}
						})(marker, i));
						
						infowindow.setContent(locations[i][0]);
						infowindow.open(map, marker);
					}
					}
				}
			});
			$(document).ready(function() {
				$('.contact-index-index .page-wrapper > #maincontent').css({"width": "100%"});
			});
		})(jQuery);
	});
	</script>
<?php endif ?>
