<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>

<?php
echo $block
    ->escapeHtml(
        $block->getData('product_name')
    )
?> ha sido agregado a tu Wish List. Click <a href="<?php
echo $block
    ->escapeUrl(
        $block->getData('referer')
    )
?>">aquí</a> para continuar cotizando.