<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php  
$objectManagerCms = \Magento\Framework\App\ObjectManager::getInstance();
$cmsPage = $objectManagerCms->get('\Magento\Cms\Model\Page');
$identifier = $cmsPage->getIdentifier();



if (strpos($identifier , 'destination') !== false) {
    $_imgUrl = "/pub/media/assets/destinations.jpg";
} elseif (strpos($identifier , 'corporate') !== false) {
	$_imgUrl = "/pub/media/assets/corporate.jpg";
} elseif (strpos($identifier , 'experiencia') !== false) {
	$_imgUrl = "/pub/media/assets/experiencias.jpg";
} elseif (strpos($identifier , 'look') !== false) {
	$_imgUrl = "/pub/media/assets/looks.jpg";
} elseif (strpos($identifier , 'showroom') !== false) {
	$_imgUrl = "/pub/media/assets/showroom.jpg";
} elseif (strpos($identifier , 'tendencia') !== false) {
	$_imgUrl = "/pub/media/assets/tendencias.jpg";
} elseif (strpos($identifier , 'plano') !== false) {
	$_imgUrl = "/pub/media/assets/planos.jpg";
} else {
	$_imgUrl = "";
}

if($_imgUrl !== "" ) {
	$_imgHtml = '<style> .breadcrumbs { background-image: url(' . $_imgUrl . ') !important;}</style>';
	/* @escapeNotVerified */ echo $_imgHtml;	
}
?>

<?php if ($crumbs && is_array($crumbs)) : ?>
<div class="breadcrumbs">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<h1 class="text-center text-uppercase">
					<?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
						<?php if ($crumbInfo['last']) : ?>
							<?php echo $block->escapeHtml($crumbInfo['label']) ?>
						<?php endif ?>
					<?php endforeach; ?>
				</h1>
				<ol class="breadcrumb text-center">
					<?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
						<?php if ($crumbInfo['link']) : ?>
							<li class="item <?php /* @escapeNotVerified */ echo $crumbName ?>">
								<a href="<?php /* @escapeNotVerified */ echo $crumbInfo['link'] ?>" title="<?php echo $block->escapeHtml($crumbInfo['title']) ?>">
									<?php echo $block->escapeHtml($crumbInfo['label']) ?>
								</a>
							</li>
						<?php elseif ($crumbInfo['last']) : ?>
							<li class="active">
								<?php echo $block->escapeHtml($crumbInfo['label']) ?>
							</li>
						<?php else: ?>
							<li class="item">
								<?php echo $block->escapeHtml($crumbInfo['label']) ?>
							</li>
						<?php endif; ?>
						
					<?php endforeach; ?>
				</ol>
			</div>
		</div>
	</div>
</div>
<?php endif; ?>
